"""Test (a): Karaka-stripped 'structural' scorer.

The Round-11 permutation test revealed that the `personal` RR=2.31 finding
is a lifecycle artifact, mechanically generated by:

    _KARAKA_MAP["personal"] = {"Moon": 1.0}

This adds a chart-INDEPENDENT +1.0 to the score whenever the active dasha
lord is Moon, which then correlates with population age distributions.

This module strips the karaka contribution entirely and reruns the
pooled + permutation analysis on the chart-DEPENDENT components only:

    relevance_structural(L, E, chart) = HR(L, E, chart) + func_mod(L, chart)
                                      (NO KR term — karaka baseline removed)

If the post-strip pooled RR retreats to ~1.0 AND its shuffled null
collapses to ~1.0, that confirms KR was the sole driver of the spurious
signal and the chart-dependent HR/func_mod components carry no signal.

If the post-strip pooled RR remains elevated AND its shuffled null
collapses to ~1.0, that would be the first evidence of genuine chart-
structural signal in this codebase.

If both stay elevated together, the lifecycle confound infects HR/func_mod
through a different mechanism than we've identified.

Usage:
    python -m app.medini.ml.dasha_doctrine_structural --event-class personal
    python -m app.medini.ml.dasha_doctrine_structural --n-perms 20
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Final

import numpy as np
import pandas as pd
from scipy.stats import norm

from app.medini.ml.dasha_doctrine_score import (
    _HOUSE_MAP, _functional_modifier, _house_resonance,
)
from app.medini.ml.dasha_doctrine_score_mix import _scorer_for
from app.medini.ml.dasha_doctrine_score_strength import dignity_strength
from app.medini.ml.dasha_doctrine_pooled import (
    _dedup_by_birth_jd, _load_corpora,
    _mantel_haenszel_log_rr, _per_corpus_rr, CorpusRR,
)
from app.medini.ml.dasha_doctrine_personal_disambiguation import (
    _shuffle_natal_charts,
)

logger = logging.getLogger(__name__)

_N_BINS: Final = 5


# --------------------------------------------------------------------------- #
# Karaka-stripped scorer                                                      #
# --------------------------------------------------------------------------- #

def doctrine_relevance_structural(
    lord: str, event_class: str, natal_row: dict,
) -> float:
    """HR + func_mod only. Drops the chart-independent KR contribution.

    The result depends on:
      - which houses the lord rules/occupies/aspects (from natal_row)
      - whether the lord is functional benefic/malefic (from rulership pattern)

    Both depend on the chart. Result: under chart shuffling, this score
    fully reshuffles — unlike the KR-laden original.
    """
    hmap = _HOUSE_MAP.get(event_class, {})
    hr = _house_resonance(lord, hmap, natal_row)
    fm = _functional_modifier(lord, natal_row)
    return hr + fm


def _s6_structural_score(
    lord: str, event_class: str, natal_row: dict,
) -> float:
    """Karaka-stripped version of the s6 scorer.

    s6_original   = (HR + KR + fmod) × dignity_strength
    s6_structural = (HR + fmod) × dignity_strength       <- this module
    """
    rel = doctrine_relevance_structural(lord, event_class, natal_row)
    sign = natal_row.get(f"sign_{lord.lower()}")
    return rel * dignity_strength(lord, sign)


def _s5_structural_score(
    lord: str, event_class: str, natal_row: dict,
) -> float:
    """Karaka-stripped version of the s5 (bare relevance) scorer."""
    return doctrine_relevance_structural(lord, event_class, natal_row)


def structural_score(
    lord: str, event_class: str, natal_row: dict,
) -> float:
    """Dispatch on the locked per-class scorer assignment, karaka-stripped."""
    scorer = _scorer_for(event_class)
    if scorer == "s5":
        return _s5_structural_score(lord, event_class, natal_row)
    if scorer == "s6":
        return _s6_structural_score(lord, event_class, natal_row)
    if scorer == "s8_3":
        # For s8_3 (triple-witness) the karaka-stripped variant is more
        # involved (KR appears inside the witness aggregation). Out of
        # scope for this test — fall back to s6 structural.
        return _s6_structural_score(lord, event_class, natal_row)
    raise ValueError(f"unknown scorer {scorer!r}")


# --------------------------------------------------------------------------- #
# Annotation                                                                  #
# --------------------------------------------------------------------------- #

def _annotate_structural(
    dasha_df: pd.DataFrame, natal_df: pd.DataFrame, event_class: str,
) -> pd.DataFrame:
    """Build the per-row structural mix_score column."""
    natal_lookup = natal_df.set_index("name_norm").to_dict("index")
    lords = ("Sun", "Moon", "Mars", "Mercury", "Jupiter", "Venus",
             "Saturn", "Rahu", "Ketu")
    per_person: dict[str, dict[str, float]] = {}
    for name, row in natal_lookup.items():
        per_person[name] = {
            lord: structural_score(lord, event_class, row) for lord in lords
        }
    names = dasha_df["name_norm"].to_numpy()
    ds_lords = dasha_df["dasha_lord"].to_numpy()
    score = np.zeros(len(dasha_df), dtype=float)
    missing = 0
    for i in range(len(dasha_df)):
        per = per_person.get(names[i])
        if per is None:
            missing += 1
            continue
        score[i] = per.get(ds_lords[i], 0.0)
    if missing:
        logger.warning("%d rows had no matching natal_lord_houses", missing)
    out = dasha_df.copy()
    out["mix_score"] = score
    out["scorer_used"] = f"{_scorer_for(event_class)}_structural"
    return out


# --------------------------------------------------------------------------- #
# Pooled + permutation                                                        #
# --------------------------------------------------------------------------- #

def _real_rrs(
    dasha_dfs: dict[str, pd.DataFrame],
    natal_dfs: dict[str, pd.DataFrame],
    event_class: str,
) -> dict[str, CorpusRR | None]:
    out: dict[str, CorpusRR | None] = {}
    for corpus, dasha_df in dasha_dfs.items():
        label_col = f"event_{event_class}"
        if label_col not in dasha_df.columns or dasha_df[label_col].sum() < 30:
            out[corpus] = None
            continue
        ann = _annotate_structural(dasha_df, natal_dfs[corpus], event_class)
        rr = _per_corpus_rr(ann, event_class, n_bins=_N_BINS)
        if rr is not None:
            rr.corpus = corpus
        out[corpus] = rr
    return out


def _shuffled_rep(
    dasha_dfs: dict[str, pd.DataFrame],
    natal_dfs: dict[str, pd.DataFrame],
    event_class: str,
    seed: int,
) -> float:
    per_corpus_rrs: list[CorpusRR] = []
    for corpus, dasha_df in dasha_dfs.items():
        label_col = f"event_{event_class}"
        if label_col not in dasha_df.columns or dasha_df[label_col].sum() < 30:
            continue
        shuffled = _shuffle_natal_charts(natal_dfs[corpus], seed=seed)
        ann = _annotate_structural(dasha_df, shuffled, event_class)
        rr = _per_corpus_rr(ann, event_class, n_bins=_N_BINS)
        if rr is None:
            continue
        rr.corpus = corpus
        per_corpus_rrs.append(rr)
    pooled = _mantel_haenszel_log_rr(per_corpus_rrs)
    return pooled["rr_pooled"]


def run(
    out_dir: Path, event_class: str = "personal", n_perms: int = 20,
) -> dict:
    out_dir.mkdir(parents=True, exist_ok=True)

    dasha_dfs, natal_dfs = _load_corpora()
    dasha_dfs, natal_dfs, n_dropped = _dedup_by_birth_jd(dasha_dfs, natal_dfs)
    logger.info("Dedup dropped %d cross-corpus duplicates", n_dropped)

    real_per_corpus = _real_rrs(dasha_dfs, natal_dfs, event_class)
    real_pooled = _mantel_haenszel_log_rr(
        [r for r in real_per_corpus.values() if r is not None]
    )
    logger.info(
        "REAL (karaka-stripped) pooled %s RR = %.3f (95%% CI %.3f-%.3f), p=%.3g",
        event_class,
        real_pooled["rr_pooled"], real_pooled["ci_low"], real_pooled["ci_high"],
        real_pooled["p"],
    )

    rng = np.random.default_rng(42)
    seeds = rng.integers(0, 2**31 - 1, size=n_perms)
    shuffled: list[float] = []
    for i, seed in enumerate(seeds, start=1):
        rr = _shuffled_rep(dasha_dfs, natal_dfs, event_class, int(seed))
        shuffled.append(rr)
        logger.info("Permutation %d/%d  shuffled_RR=%.3f", i, n_perms, rr)

    arr = np.array(shuffled)
    log_real = np.log(real_pooled["rr_pooled"])
    log_shuf = np.log(arr[~np.isnan(arr) & (arr > 0)])
    null_mean_log = float(np.mean(log_shuf))
    null_std_log = float(np.std(log_shuf, ddof=1))
    z = (log_real - null_mean_log) / null_std_log if null_std_log > 0 else float("nan")
    p_one = float(1.0 - norm.cdf(z)) if not np.isnan(z) else float("nan")
    n_exceed = int(np.sum(arr >= real_pooled["rr_pooled"]))
    emp_p = (n_exceed + 1) / (n_perms + 1)

    summary = {
        "event_class": event_class,
        "scorer": f"{_scorer_for(event_class)}_structural",
        "n_permutations": n_perms,
        "real_per_corpus_rr": {
            c: (r.rr if r is not None else None)
            for c, r in real_per_corpus.items()
        },
        "real_pooled_rr": real_pooled["rr_pooled"],
        "real_pooled_p": real_pooled["p"],
        "real_pooled_ci_low": real_pooled["ci_low"],
        "real_pooled_ci_high": real_pooled["ci_high"],
        "real_pooled_q_p": real_pooled["q_p"],
        "shuffled_distribution": {
            "mean": float(np.exp(null_mean_log)),
            "log_std": null_std_log,
            "min": float(np.min(arr)),
            "max": float(np.max(arr)),
            "median": float(np.median(arr)),
            "all_values": [float(x) for x in arr],
        },
        "z_score_real_vs_null": float(z),
        "p_value_real_vs_null": p_one,
        "empirical_p_value": emp_p,
        "n_shuffled_exceeding_real": n_exceed,
    }

    (out_dir / "structural_test.json").write_text(
        json.dumps(summary, indent=2, default=str), encoding="utf-8"
    )

    lines = [
        f"# Test (a): Karaka-stripped scorer — `{event_class}` event class",
        "",
        f"Scorer: **{summary['scorer']}** (HR + func_mod only; no KR)",
        "",
        "## Real pooled RR (karaka-stripped)",
        "",
        f"- Per-corpus: " + ", ".join(
            f"{c}={r.rr:.2f}" if r is not None else f"{c}=NA"
            for c, r in real_per_corpus.items()
        ),
        f"- Pooled: **{real_pooled['rr_pooled']:.3f}** "
        f"(95% CI {real_pooled['ci_low']:.2f}-{real_pooled['ci_high']:.2f}), "
        f"p={real_pooled['p']:.3g}, Q_p={real_pooled['q_p']:.3g}",
        "",
        "## Shuffled-chart null distribution (K=20)",
        "",
        f"| Statistic | Value |",
        f"|---|---|",
        f"| mean | {summary['shuffled_distribution']['mean']:.3f} |",
        f"| min  | {summary['shuffled_distribution']['min']:.3f} |",
        f"| median | {summary['shuffled_distribution']['median']:.3f} |",
        f"| max  | {summary['shuffled_distribution']['max']:.3f} |",
        "",
        f"## Verdict",
        "",
        f"- z-score real vs null: **{z:.2f}**",
        f"- empirical p-value:    **{emp_p:.3g}**",
        f"- n shuffled ≥ real:    {n_exceed}/{n_perms}",
        "",
    ]
    if not np.isnan(z) and z > 3:
        lines.append("> ✅ **STRUCTURAL CHART SIGNAL CONFIRMED** — the "
                     "karaka-stripped scorer's RR survives chart shuffling "
                     "with high z. This is the first robust evidence of "
                     "structural astronomical signal in this corpus.")
    elif (real_pooled["rr_pooled"] < 1.2 and
          summary["shuffled_distribution"]["mean"] < 1.2):
        lines.append("> 🚫 **BOTH COLLAPSE TO ~1.0** — stripping karaka kills "
                     "the real RR alongside the shuffled null. This confirms "
                     "the chart-DEPENDENT components (HR + func_mod) carry no "
                     "signal; the original RR=2.31 was 100% karaka-driven "
                     "lifecycle confound.")
    elif not np.isnan(z) and z < 1:
        lines.append("> ⚠️ **PERSISTENT LIFECYCLE LEAKAGE** — even with karaka "
                     "stripped, the shuffled null tracks the real RR. The "
                     "lifecycle confound enters via HR or func_mod through "
                     "some other mechanism (likely func_mod's rulership-"
                     "dependence on chart-pattern frequencies).")
    else:
        lines.append("> 🤔 **PARTIAL** — real RR exceeds the null but margin "
                     "is small. Larger K recommended.")
    lines.append("")
    (out_dir / "structural_test.md").write_text("\n".join(lines), encoding="utf-8")
    logger.info("Wrote %s", out_dir / "structural_test.md")
    return summary


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m app.medini.ml.dasha_doctrine_structural",
        description="Karaka-stripped scorer pooled + permutation test.",
    )
    parser.add_argument("--out", type=Path,
                        default=Path("data/ml_runs/round11_structural_test"))
    parser.add_argument("--event-class", type=str, default="personal")
    parser.add_argument("--n-perms", type=int, default=20)
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
    )
    summary = run(args.out, event_class=args.event_class, n_perms=args.n_perms)
    print()
    print(f"=== Test (a): Karaka-stripped scorer ({args.event_class}) ===")
    print(f"  real per-corpus:  {summary['real_per_corpus_rr']}")
    print(f"  real pooled RR:   {summary['real_pooled_rr']:.3f}  p={summary['real_pooled_p']:.3g}")
    print(f"  shuffled mean:    {summary['shuffled_distribution']['mean']:.3f}")
    print(f"  shuffled max:     {summary['shuffled_distribution']['max']:.3f}")
    print(f"  z (real vs null): {summary['z_score_real_vs_null']:.2f}")
    print(f"  empirical p:      {summary['empirical_p_value']:.3g}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
