"""Generate _TARGETS_MASTER_SCORECARD.csv comparing every trained target run.

For each `data/ml_runs/<target>_<ts>/` directory, recomputes SHAP values on
the deterministic holdout split (seed=42), computes Pearson correlation
between each top-3 feature's SHAP and the row's birth year, and emits a
row to the master scorecard with the era-confound flag set per the
detection rule defined in the Phase 5 round-2 plan:

    flag confounded ⇔ any feature in
    {dist_jupiter_saturn, dist_saturn_rahu, dist_jupiter_rahu,
     lon_rahu, lon_ketu, lon_saturn, lon_jupiter,
     lat_saturn, dec_saturn}
    appears in the top-3 by mean |SHAP| AND has |pearsonr(SHAP, year)| > 0.4

The gap-based heuristic (`holdout_auc - cv_auc > 0.04`) does NOT detect
era-confounding because our 80/20 split is randomized and stratified —
birth years distribute uniformly across train and test, so era markers
perform identically well on both sides.

The script is read-only relative to the trained runs (only adds the
scorecard file). It does NOT retrain anything — it loads model.json +
feature_columns.json and uses TreeExplainer for SHAP.

CLI:
    python scripts/generate_target_scorecard.py \\
        --runs-dir data/ml_runs \\
        --parquet  app/medini/data/ml_astro_with_lunar.parquet \\
        --merged-csv data/astro_databank/merged_with_lunar.csv \\
        --output data/ml_runs/_TARGETS_MASTER_SCORECARD.csv
"""
from __future__ import annotations

import argparse
import csv
import datetime as dt
import json
import logging
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd
import scipy.stats
import shap
import xgboost as xgb

from app.medini.ml.train_classifier import (
    NON_FEATURE_COLUMNS,
    derive_binary_target,
    select_features,
)

logger = logging.getLogger(__name__)

# Outer-planet features whose presence in top-3 + high birth-year correlation
# strongly suggests temporal confounding. Saturn-cycle markers (every ~29 yr),
# Rahu-cycle markers (~18 yr), Jupiter-cycle markers (~12 yr) all encode era.
OUTER_PLANET_FEATURES: frozenset[str] = frozenset({
    "dist_jupiter_saturn",
    "dist_saturn_rahu",
    "dist_jupiter_rahu",
    "lon_rahu",
    "lon_ketu",
    "lon_saturn",
    "lon_jupiter",
    "lat_saturn",
    "dec_saturn",
})

# Threshold above which a top-3 outer-planet feature is flagged confounded.
ERA_CORRELATION_THRESHOLD: float = 0.4

# Run-dir name format: <safe_target>_<YYYYMMDDTHHMMSSZ>
_RUN_DIR_RE = re.compile(r"^(?P<target>[A-Za-z0-9_]+)_(?P<ts>\d{8}T\d{6}Z)$")
_DATE_RE = re.compile(r"^(\d{4})-(\d{1,2})-(\d{1,2})")

_REPORT_AUC_RE = re.compile(
    r"(?:Cross-validation|CV)\s+ROC-AUC[^:]*:\s*(?P<cv>[\d.]+)\s*[±+\-]?\s*(?P<std>[\d.]+)?",
    re.IGNORECASE,
)
_REPORT_TEST_AUC_RE = re.compile(
    r"Holdout\s+test\s+ROC-AUC[^:]*:\s*(?P<auc>[\d.]+)",
    re.IGNORECASE,
)
_REPORT_BASE_RATE_RE = re.compile(
    r"Base\s+positive\s+rate[^:]*:\s*(?P<rate>[\d.]+)\s*%",
    re.IGNORECASE,
)


# ---------- Run-directory metadata ----------

def parse_run_metadata(run_dir: Path) -> dict | None:
    """Extract target name + timestamp from the run-dir naming convention.
    Returns None if the directory name doesn't conform."""
    m = _RUN_DIR_RE.match(run_dir.name)
    if not m:
        return None
    return {"target": m.group("target"), "timestamp": m.group("ts")}


def read_report_metrics(run_dir: Path) -> dict:
    """Pull AUC + base rate from report.md (auto-generated by the trainer).
    Falls back to empty values if report.md is missing or malformed."""
    report_path = run_dir / "report.md"
    out = {
        "cv_auc_mean": None,
        "cv_auc_std": None,
        "test_auc": None,
        "base_rate": None,
    }
    if not report_path.exists():
        return out
    text = report_path.read_text(encoding="utf-8", errors="replace")
    m = _REPORT_AUC_RE.search(text)
    if m:
        out["cv_auc_mean"] = float(m.group("cv"))
        if m.group("std"):
            out["cv_auc_std"] = float(m.group("std"))
    m = _REPORT_TEST_AUC_RE.search(text)
    if m:
        out["test_auc"] = float(m.group("auc"))
    m = _REPORT_BASE_RATE_RE.search(text)
    if m:
        out["base_rate"] = float(m.group("rate")) / 100.0
    return out


def read_top_features(run_dir: Path, n: int = 5) -> list[str]:
    """Read top-N feature names from feature_importance.csv."""
    fi_path = run_dir / "feature_importance.csv"
    if not fi_path.exists():
        return []
    features: list[str] = []
    with fi_path.open("r", encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            features.append(row.get("feature", ""))
            if len(features) >= n:
                break
    return features


def read_top_calibrated_rule_pp(run_dir: Path) -> float | None:
    """Return the calibrated probability shift (percentage points) of the
    highest-impact rule, or None if rules.csv has no rules. Useful for the
    scorecard to surface "this target's strongest discovered rule shifts
    probability by N pp" without needing to re-run rule extraction."""
    rules_path = run_dir / "rules.csv"
    if not rules_path.exists():
        return None
    top_delta = None
    with rules_path.open("r", encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            try:
                delta = float(row.get("probability_delta", "0"))
            except (ValueError, TypeError):
                continue
            if top_delta is None or abs(delta) > abs(top_delta):
                top_delta = delta
    return top_delta * 100.0 if top_delta is not None else None  # to pp


# ---------- Birth-year lookup ----------

def build_name_to_year_map(merged_csv: Path) -> dict[str, int]:
    """Read the source raw.csv used by Stage 2 ETL, parse date_of_birth →
    int year. Keys on the trimmed `name` column. Duplicate names overwrite
    (we only need a representative year per name; multi-spelling collisions
    are rare and won't matter for era-confound detection)."""
    if not merged_csv.exists():
        raise FileNotFoundError(f"merged source CSV missing: {merged_csv}")
    mapping: dict[str, int] = {}
    csv.field_size_limit(10 ** 7)
    with merged_csv.open("r", encoding="utf-8", newline="") as f:
        for row in csv.DictReader(f):
            name = (row.get("name") or "").strip()
            dob = (row.get("date_of_birth") or "").strip()
            if not (name and dob):
                continue
            m = _DATE_RE.match(dob)
            if not m:
                continue
            try:
                year = int(m.group(1))
            except ValueError:
                continue
            mapping[name] = year
    return mapping


# ---------- SHAP × birth_year correlation ----------

def compute_top_feature_year_correlations(
    run_dir: Path,
    parquet_path: Path,
    name_to_year: dict[str, int],
    n_top: int = 3,
    seed: int = 42,
) -> tuple[list[tuple[str, float]], dict[str, float | int | None]]:
    """For the top-N features by importance, compute Pearson |r| between
    that feature's per-row SHAP value and the row's birth year.

    Returns (correlations, metrics) where:
      correlations = [(feature_name, pearson_r), ...]
      metrics      = {"n_rows_with_year": int, "fraction_with_year": float}

    Side-effect free: loads model + parquet but writes nothing.
    """
    # Load model
    clf = xgb.XGBClassifier(enable_categorical=True)
    clf.load_model(str(run_dir / "model.json"))

    # Reconstruct X via the same select_features() the trainer used
    df = pd.read_parquet(parquet_path)

    # Derive target from the run-dir name so the train/test split matches
    parsed = parse_run_metadata(run_dir)
    if parsed is None:
        return [], {"n_rows_with_year": 0, "fraction_with_year": 0.0}
    target = parsed["target"]

    try:
        y = derive_binary_target(df, target)
    except Exception:
        # If derive fails (target string changed since the run), still compute
        # SHAP on the full parquet without train/test split.
        y = None

    X = select_features(df)
    # Recover the train/test split with the same seed the trainer used.
    if y is not None and y.sum() >= 5:
        from sklearn.model_selection import train_test_split
        _, X_test, _, _ = train_test_split(
            X, y, test_size=0.2, stratify=y, random_state=seed,
        )
    else:
        X_test = X

    # Compute SHAP on the holdout
    explainer = shap.TreeExplainer(clf)
    sv = explainer.shap_values(X_test)
    if isinstance(sv, list):
        sv = sv[1]
    shap_arr = np.asarray(sv)

    # Identify top-N features by mean |SHAP|
    importances = np.abs(shap_arr).mean(axis=0)
    feature_names_test = list(X_test.columns)
    ranked_idx = np.argsort(importances)[::-1]

    # Map X_test rows to birth years via the parquet's `name` column
    name_col = df["name"].iloc[X_test.index].astype(str).values
    years = np.array([
        name_to_year.get(n.strip(), np.nan) for n in name_col
    ], dtype=float)
    valid_mask = ~np.isnan(years)
    n_with_year = int(valid_mask.sum())

    correlations: list[tuple[str, float]] = []
    for i in ranked_idx[:n_top]:
        feature_name = feature_names_test[i]
        shap_col = shap_arr[:, i]
        if n_with_year >= 30:
            r, _ = scipy.stats.pearsonr(shap_col[valid_mask], years[valid_mask])
            correlations.append((feature_name, float(r)))
        else:
            correlations.append((feature_name, float("nan")))

    metrics = {
        "n_rows_with_year": n_with_year,
        "fraction_with_year": (
            float(n_with_year) / max(len(X_test), 1)
        ),
    }
    return correlations, metrics


def is_era_confounded(
    correlations: list[tuple[str, float]],
    threshold: float = ERA_CORRELATION_THRESHOLD,
) -> tuple[bool, float | None]:
    """Apply the era-confound rule. Returns (flag, max_abs_r_for_outer).

    Flagged if ANY outer-planet feature in the top-3 has |r| >= threshold.
    """
    max_abs_r: float | None = None
    flag = False
    for feature_name, r in correlations:
        if feature_name in OUTER_PLANET_FEATURES:
            ar = abs(r) if not np.isnan(r) else 0.0
            if max_abs_r is None or ar > max_abs_r:
                max_abs_r = ar
            if ar >= threshold:
                flag = True
    return flag, max_abs_r


# ---------- Scorecard generation ----------

def generate_scorecard(
    runs_dir: Path,
    parquet_path: Path,
    merged_csv: Path,
    output_csv: Path,
) -> int:
    """Walk every run dir, build the master comparison CSV. Returns row count."""
    if not runs_dir.exists():
        raise FileNotFoundError(f"runs dir missing: {runs_dir}")

    logger.info("Building name→year map from %s", merged_csv)
    name_to_year = build_name_to_year_map(merged_csv)
    logger.info("Year-map size: %d names", len(name_to_year))

    rows: list[dict] = []
    run_dirs = sorted([d for d in runs_dir.iterdir() if d.is_dir()])
    for run_dir in run_dirs:
        meta = parse_run_metadata(run_dir)
        if meta is None:
            continue
        if not (run_dir / "model.json").exists():
            continue
        if not (run_dir / "feature_columns.json").exists():
            # Pre-Fix runs may lack the schema artifact; skip era-confound
            # check for those (correlations need the model to score)
            logger.warning("Skipping %s — no feature_columns.json", run_dir.name)
            continue

        logger.info("Scoring %s", run_dir.name)
        report = read_report_metrics(run_dir)
        top_features = read_top_features(run_dir, n=5)
        top_rule_pp = read_top_calibrated_rule_pp(run_dir)

        try:
            correlations, year_metrics = compute_top_feature_year_correlations(
                run_dir, parquet_path, name_to_year,
            )
        except Exception:
            logger.exception("SHAP correlation failed for %s", run_dir.name)
            correlations = []
            year_metrics = {"n_rows_with_year": 0, "fraction_with_year": 0.0}

        era_flag, era_max_abs_r = is_era_confounded(correlations)

        rows.append({
            "target": meta["target"],
            "timestamp_utc": meta["timestamp"],
            "run_dir": run_dir.name,
            "cv_auc_mean": report["cv_auc_mean"],
            "cv_auc_std": report["cv_auc_std"],
            "test_auc": report["test_auc"],
            "base_rate": report["base_rate"],
            "top_5_features": ";".join(top_features),
            "top_3_year_correlations": ";".join(
                f"{f}={r:+.3f}" for f, r in correlations
            ),
            "era_confounded_flag": era_flag,
            "era_max_abs_r_outer": era_max_abs_r,
            "n_holdout_with_year": year_metrics["n_rows_with_year"],
            "top_rule_calibrated_pp": top_rule_pp,
        })

    output_csv.parent.mkdir(parents=True, exist_ok=True)
    fieldnames = list(rows[0].keys()) if rows else [
        "target", "timestamp_utc", "run_dir", "cv_auc_mean", "cv_auc_std",
        "test_auc", "base_rate", "top_5_features",
        "top_3_year_correlations", "era_confounded_flag",
        "era_max_abs_r_outer", "n_holdout_with_year",
        "top_rule_calibrated_pp",
    ]
    with output_csv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        for row in rows:
            writer.writerow(row)

    return len(rows)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python scripts/generate_target_scorecard.py",
        description="Generate the master comparison CSV across all trained targets.",
    )
    parser.add_argument("--runs-dir", type=Path, default=Path("data/ml_runs"))
    parser.add_argument(
        "--parquet", type=Path,
        default=Path("app/medini/data/ml_astro_with_lunar.parquet"),
    )
    parser.add_argument(
        "--merged-csv", type=Path,
        default=Path("data/astro_databank/merged_with_lunar.csv"),
        help="Source raw.csv from which the parquet was built, used for "
             "name → birth-year lookup.",
    )
    parser.add_argument(
        "--output", type=Path,
        default=Path("data/ml_runs/_TARGETS_MASTER_SCORECARD.csv"),
    )
    parser.add_argument("-v", "--verbose", action="store_true")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
    )

    count = generate_scorecard(
        runs_dir=args.runs_dir,
        parquet_path=args.parquet,
        merged_csv=args.merged_csv,
        output_csv=args.output,
    )
    logger.info("Wrote %d rows to %s", count, args.output)
    return 0


if __name__ == "__main__":
    sys.exit(main())
