"""Phase 9.5 — render a framework Reading as prose Interpretation objects.

Bridges the Phase 9 ``Reading`` dataclass (structured claims + citations
+ DKP modulation) into the existing ``Interpretation`` contract used by
``app/llm/interpreter.py`` and the UI templates. The bridge has two
modes:

* **Deterministic fallback** (no LLM required) — composes prose from
  the structured ``ReadingClaim`` fields with classical citations
  inlined as ``[Ref N]`` markers. Always works, suitable for tests and
  offline environments.
* **LLM-augmented** — the deterministic prose seeds a prompt the LLM
  refines for fluency while preserving the citation anchors. Falls back
  silently to deterministic when no LLM client is provided or the call
  fails.

## Why two layers

The Phase 9 ``Reading`` is the doctrinally-faithful source of truth.
The LLM never *invents* claims — it only *rephrases* the structured
verdicts. Citations are derived from ``ReadingClaim.citations`` (which
came from ``Reasoning.reference`` set by Phases 1-8), not generated by
the LLM. This means the framework's prose layer is auditable against
the source of every sentence.
"""
from __future__ import annotations

from typing import Final

from app.core.reading_composer import Reading, ReadingClaim
from app.llm.interpreter import (
    Citation,
    Interpretation,
    InterpretMode,
    LLMClient,
)


_BHAVA_NAMES: Final[dict[int, str]] = {
    1: "Tanu (self, body, identity)",
    2: "Dhana (wealth, family, voice)",
    3: "Bhratru (siblings, courage, short journeys)",
    4: "Sukha (home, mother, comforts)",
    5: "Putra (children, intellect, prior karma)",
    6: "Ari (enemies, disease, debt, service)",
    7: "Yuvati (spouse, partnerships, business)",
    8: "Ayur (longevity, transformation, hidden matters)",
    9: "Dharma (father, fortune, higher learning)",
    10: "Karma (career, status, action)",
    11: "Labha (gains, income, networks)",
    12: "Vyaya (loss, expenditure, moksha, foreign)",
}


def _citations_from_claim(claim: ReadingClaim) -> tuple[Citation, ...]:
    """Map a claim's classical references to UI Citation objects."""
    return tuple(
        Citation(
            source="bphs-doctrine",
            title=ref,
            snippet=f"Classical anchor for bhava {claim.bhava}: {ref}",
            source_url=None,
            local_path=None,
            score=1.0,
        )
        for ref in claim.citations
    )


def _label_verdict(label: str) -> str:
    """Human-friendly verdict phrasing."""
    return {
        "strong": "promises strongly",
        "medium": "carries moderate promise",
        "weak": "is afflicted",
        "afflicted": "is significantly afflicted",
    }.get(label, "is mixed in promise")


def _trigger_phrase(claim: ReadingClaim) -> str:
    """Optional gochara-trigger phrase, empty if not triggered."""
    if not claim.gochara_triggered:
        return ""
    return (
        " The current transit double-trigger (Saturn + Jupiter both "
        "touching this bhava or its lord/karaka) activates this promise NOW."
    )


def _confidence_phrase(claim: ReadingClaim) -> str:
    """Suffix indicating reading confidence."""
    return {
        "LOW": " (Confidence: LOW — limited context.)",
        "MEDIUM": " (Confidence: MEDIUM.)",
        "HIGH": " (Confidence: HIGH — full context provided.)",
    }.get(claim.confidence, "")


def deterministic_bhava_section(
    reading: Reading, bhava: int,
) -> Interpretation:
    """Render one bhava as structured prose without LLM.

    The text is composed from the ``ReadingClaim`` fields directly;
    each finding is paraphrased and citation markers ``[Ref N]``
    correspond to entries in the returned ``citations`` tuple.
    """
    claim = reading.bhava_claims.get(bhava)
    if claim is None:
        return Interpretation(
            text=f"No claim available for bhava {bhava}.",
            mode="section", section=str(bhava),
            source="fallback", model=None, citations=(),
        )

    name = _BHAVA_NAMES.get(bhava, f"Bhava {bhava}")
    verdict = _label_verdict(claim.verdict_label)
    focus = claim.reading_focus
    trigger = _trigger_phrase(claim)
    confidence = _confidence_phrase(claim)

    lines = [
        f"**Bhava {bhava} — {name}**",
        "",
        f"The reading focus for this bhava is: *{focus}*.",
        "",
        f"This bhava {verdict} (composite score {claim.composite_score:+.2f}).",
    ]
    if claim.confirming_yogas:
        lines.append(
            f"Confirming yogas active for this bhava: "
            f"{', '.join(claim.confirming_yogas)}."
        )
    if claim.afflicting_yogas:
        lines.append(
            f"Afflicting patterns active: "
            f"{', '.join(claim.afflicting_yogas)}."
        )
    if claim.key_findings:
        lines.append("")
        lines.append("Key findings (most-weighted first):")
        for i, finding in enumerate(claim.key_findings, start=1):
            ref_marker = f" [Ref {i}]" if i <= len(claim.citations) else ""
            lines.append(f"  {i}. {finding}.{ref_marker}")
    if claim.modulation_notes:
        lines.append("")
        lines.append("Context modulations:")
        for n in claim.modulation_notes:
            lines.append(f"  - {n}")
    lines.append(trigger.strip())
    text = "\n".join(line for line in lines if line.strip())
    text = text + confidence

    return Interpretation(
        text=text,
        mode="section",
        section=str(bhava),
        source="fallback",
        model=None,
        citations=_citations_from_claim(claim),
    )


def deterministic_summary(reading: Reading) -> Interpretation:
    """Render the chart-level overall summary without LLM."""
    lines = [
        "## Astrologer's-Lens Reading Summary",
        "",
        reading.chart_strength_summary,
        "",
        f"Lagna sign {reading.asc_sign}, ruled by {reading.asc_lagna_lord}. "
        f"Yogakaraka planets for this Lagna: "
        f"{', '.join(reading.yogakarakas) if reading.yogakarakas else 'none'}. "
        f"Badhakesh (obstruction lord) is {reading.badhakesh}.",
        "",
        f"Strongest planet: {reading.strongest_planet}. "
        f"Weakest planet: {reading.weakest_planet}.",
        "",
        f"DKP context completeness: {reading.dkp_completeness}/12.",
    ]
    if reading.active_yogas:
        lines.append("")
        lines.append("Active classical yogas:")
        for y in reading.active_yogas:
            lines.append(
                f"  - **{y.name}** (intensity {y.intensity:.2f}) — {y.reference}"
            )
    if reading.vimshottari_md_at_target:
        lines.append("")
        lines.append(
            f"Active Vimshottari MD: {reading.vimshottari_md_at_target}. "
            f"Active Chara MD (sign): "
            f"{reading.chara_md_at_target or 'not provided'}."
        )
    if reading.open_questions:
        lines.append("")
        lines.append("Open clarifying questions (context-insufficient):")
        for q in reading.open_questions:
            lines.append(f"  ? {q}")

    text = "\n".join(lines)
    # Build a compact citation set from the active yogas.
    citations = tuple(
        Citation(
            source="bphs-doctrine", title=y.reference,
            snippet=f"{y.name}: {y.description}",
            source_url=None, local_path=None, score=y.intensity,
        )
        for y in reading.active_yogas
    )
    return Interpretation(
        text=text, mode="summary", section=None,
        source="fallback", model=None, citations=citations,
    )


def _build_llm_prompt_for_section(
    reading: Reading, claim: ReadingClaim,
) -> str:
    """Prompt that asks the LLM to refine deterministic prose while
    preserving the structured claims + citations.

    The LLM's job is NOT to invent claims — only to rephrase the
    existing structured findings into a flowing paragraph. We instruct
    it explicitly.
    """
    name = _BHAVA_NAMES.get(claim.bhava, f"Bhava {claim.bhava}")
    findings_bullets = "\n".join(f"- {f}" for f in claim.key_findings)
    citations_block = "\n".join(f"  [{ref}]" for ref in claim.citations)
    yogas_block = ""
    if claim.confirming_yogas:
        yogas_block = (
            f"Confirming yogas: {', '.join(claim.confirming_yogas)}\n"
        )
    notes_block = ""
    if claim.modulation_notes:
        notes_block = "Context modulations:\n" + "\n".join(
            f"  {n}" for n in claim.modulation_notes
        )
    return f"""You are a doctrine-faithful Vedic astrology reading assistant.
Rephrase the structured analysis below into 4-6 flowing sentences of clear
English for this bhava. Do NOT invent new claims, planet positions, or
yogas — only reword what is given. Preserve the verdict label and
reference markers exactly.

Bhava {claim.bhava} ({name}) — verdict: {claim.verdict_label}
Reading focus: {claim.reading_focus}
Composite score: {claim.composite_score:+.2f}
Confidence: {claim.confidence}

Findings (do not add, only refine):
{findings_bullets}

{yogas_block}{notes_block}

Classical references (cite these only — no others):
{citations_block}
""".strip()


def interpret_bhava(
    reading: Reading, bhava: int, *, client: LLMClient | None = None,
) -> Interpretation:
    """Render one bhava as an Interpretation — LLM if available, else fallback."""
    fallback = deterministic_bhava_section(reading, bhava)
    if client is None:
        return fallback
    claim = reading.bhava_claims.get(bhava)
    if claim is None:
        return fallback
    try:
        prompt = _build_llm_prompt_for_section(reading, claim)
        response = client.complete(prompt)
        if not response or not response.strip():
            return fallback
        return Interpretation(
            text=response.strip(),
            mode="section",
            section=str(bhava),
            source="llm",
            model=getattr(client, "model", None),
            citations=fallback.citations,
        )
    except Exception:  # noqa: BLE001 — LLM call may fail any number of ways
        return fallback


def interpret_reading(
    reading: Reading, *, client: LLMClient | None = None,
) -> tuple[Interpretation, ...]:
    """Full chart rendering — one summary + 12 bhava sections."""
    out: list[Interpretation] = [deterministic_summary(reading)]
    for b in range(1, 13):
        out.append(interpret_bhava(reading, b, client=client))
    return tuple(out)
